# Generated by Django 4.2.7 on 2025-05-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('sender', models.EmailField(max_length=254, verbose_name='Remetente')),
                ('category', models.CharField(blank=True, choices=[('productive', 'Produtivo'), ('unproductive', 'Improdutivo')], max_length=20, verbose_name='Categoria')),
                ('suggested_response', models.TextField(blank=True, verbose_name='Resposta Sugerida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['-created_at'],
            },
        ),
    ]
