services:
  django:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: email-classifier-django
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    env_file:
      - .env
    networks:
      - email-classifier-network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: email-classifier-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - email-classifier-network
    depends_on:
      - django

networks:
  email-classifier-network:
    driver: bridge
