[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
dependsOn = ["setup"]
cmds = ["cd server && pip install --break-system-packages -r requirements.txt"]

[start]
cmd = "cd server && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:$PORT"

[variables]
PYTHONPATH = "./server"
