[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
dependsOn = ["setup"]
cmds = ["cd server && pip install --break-system-packages -r requirements.txt"]

[phases.build]
dependsOn = ["install"]
cmds = ["cd server && python manage.py collectstatic --noinput"]

[start]
cmd = "cd server && python manage.py migrate && gunicorn email_classifier.wsgi:application --bind 0.0.0.0:$PORT --workers 2"

[variables]
PYTHONPATH = "./server"
