[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
dependsOn = ["setup"]
cmds = ["cd server && pip install --break-system-packages -r requirements.txt"]

[start]
cmd = "chmod +x start.sh && ./start.sh"

[variables]
PYTHONPATH = "./server"
