# Generated by Django 4.2.7 on 2025-05-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0005_email_classification_method'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['category'], name='classifier__categor_a8a30b_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['created_at'], name='classifier__created_645eac_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['sender'], name='classifier__sender_85ffd9_idx'),
        ),
    ]
